# Tanuki Theme - Book Mode Example
base_url = "/tanuki/book"
title = "The Tanuki Guide"
description = "E-book example for the Tanuki theme"
theme = "tanuki"
compile_sass = true
build_search_index = true
generate_feeds = false

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
mode = "book"
github = "https://github.com/lokeshmohanty/tanuki"
show_theme_toggle = true
